---
title: "Tarea 2"
subtitle: "Pseudoalineamientos"
author: "Pablo Salazar-Méndez"
date: "2026-04-15"
crossref:
  fig-title: "Figura"
  tbl-title: "Tabla"
format:
  pdf:
    pdf-engine: xelatex
    mainfont: "Arial"
    fontsize: 12pt
    toc: true
    toc-depth: 3
    number-sections: true
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \renewcommand{\figurename}{Figura}
---

# Planteamiento

El análisis de datos de RNA-seq requiere, como paso fundamental, la cuantificación de la abundancia de los transcritos, ya que a partir de esta medida es posible inferir niveles de expresión génica y realizar comparaciones entre condiciones biológicas. Para ello, existen dos enfoques principales que difieren en su manera de procesar las lecturas de secuenciación: los métodos basados en alineamientos, que buscan ubicar cada lectura en una posición específica del genoma o transcriptoma, y los métodos de pseudoalineamiento, que asignan las lecturas a posibles transcritos de manera más eficiente sin realizar un alineamiento completo.

Este escrito busca mostrar brevemente el procedimiento usual tanto para la cuantificación tanto por alineamientos (con `featureCounts`) como por pseudoalineamientos (`Salmon`), en vísperas de cuantificar la abundancia de los transcritos desde datos de expresión.

# Metodología & justificación

Si bien todos los scripts utilizados se muestran en las secciones subsecuentes, la totalidad del proyecto se ubica en el servidor Chaac dentro del directorio `/export/space3/users/pablosm/2026-2/Transcriptomica_clase` y en el siguiente [repositorio de GitHub](https://github.com/pablomics-004/Transcriptomica_clase).

## 1. Filtrado y ordenamiento de los archivos `BAM` mediante `samtools`

En esta sección se realiza el procesamiento de los archivos de alineamiento obtenidos previamente, estandarizando su formato y preparándolos para análisis posteriores. Específicamente, se recorre cada conjunto de resultados provenientes de distintos alineadores (HISAT2 y STAR, en configuraciones PE y SE), convirtiendo los archivos SAM a formato BAM cuando es necesario, y posteriormente aplicando un filtrado por calidad y eliminación de lecturas no alineadas. Los archivos resultantes se ordenan, se indexan y se almacenan en directorios organizados, generando así archivos BAM filtrados.

```{shell Filtrado_ordenamiento de BAM y generación de index}
#| eval: false
#| echo: true

#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

# Directorios de trabajo
RESULTS="./results"

declare -A rutas
rutas[HISAT2_PE]="${RESULTS}/hisat2_pe"
rutas[HISAT2_SE]="${RESULTS}/hisat2_se"
rutas[STAR_PE]="${RESULTS}/star_pe"
rutas[STAR_SE]="${RESULTS}/star_se"

# Variables útiles
SAM="sam"
BAM="bam"
SORTED="bam_filtered_sorted"
wks=8

echo "================================================================================================="
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Iniciando conversión de SAM a BAM, filtrado y ordenamiento - $current_date_time"

# Iterando sobre las rutas
for key in "${!rutas[@]}"; do
    echo "-------------------------------------------------------------------------------------------------"
    ruta="${rutas[$key]}"

    RAW_BAM_DIR="${ruta}/${BAM^^}"
    SORTED_DIR="${ruta}/${SORTED^^}"

    mkdir -p "$RAW_BAM_DIR" "$SORTED_DIR"

    # Archivos de entrada y salida dependiendo del alineador
    if [[ "$key" == HISAT2* ]]; then
        INPUT_DIR="${ruta}/${SAM^^}"
        ARCHIVOS=("$INPUT_DIR"/*.sam)

        echo "Procesando directorio ${INPUT_DIR}/"
        echo "Alineamientos de HISAT2"

    else
        INPUT_DIR="${ruta}/${BAM^^}"
        ARCHIVOS=("$INPUT_DIR"/*.bam)

        echo "Procesando directorio ${INPUT_DIR}/"
        echo "Alineamientos de STAR"
    fi

    # Iterando sobre el arreglo con los archivos
    for f in "${ARCHIVOS[@]}"; do
        if [[ "$key" == HISAT2* ]]; then
            base="$(basename "$f" .sam)"
            RAW_BAM="${RAW_BAM_DIR}/${base}.bam"
        else
            base="$(basename "$f" .bam)"
            RAW_BAM="$f"
        fi

        SORTED_BAM="${SORTED_DIR}/${base}_filtered_sorted.bam"

        echo "Procesando archivo: $f"

        tmp_dir=$(mktemp -d)

        # Sólo HISAT2_(SE|PE) no tiene BAM crudo
        if [[ "$key" == HISAT2* ]]; then
            echo "Convirtiendo SAM a BAM crudo: $RAW_BAM"
            if ! samtools view -bS "$f" > "$RAW_BAM"; then
                echo "[ERROR] Fallo al convertir SAM a BAM con samtools view en $f" >&2
                rm -rf "$tmp_dir"
                exit 1
            fi
        fi

        echo "-------------------------------------------------------------------------------------------------"

        echo "Filtrando y ordenando hacia: $SORTED_BAM"
        if samtools view -F 4 -q 10 -u "$RAW_BAM" | \
           samtools sort -@ $wks -T "${tmp_dir}/sort" -o "$SORTED_BAM"; then
            echo "Procesado con éxito: $f"
        else
            echo "[ERROR] Falló al filtrar/ordenar con samtools en $f" >&2
            rm -rf "$tmp_dir"
            exit 1
        fi

        echo "-------------------------------------------------------------------------------------------------"

        echo "Indexando BAM: $SORTED_BAM"
        if samtools index -@ $wks "$SORTED_BAM"; then
            echo "Índice generado: ${SORTED_BAM}.bai"
        else
            echo "[ERROR] Falló el indexado de $SORTED_BAM" >&2
            rm -rf "$tmp_dir"
            exit 1
        fi

        rm -rf "$tmp_dir"
    done
done

echo "-------------------------------------------------------------------------------------------------"
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Script finalizado con éxito - $current_date_time"
echo "================================================================================================="
```

## 2. Pileups

Tomando los BAM procesados como entrada es que se generan archivos de cobertura (pileups) para representar la señal de alineamiento a lo largo del genoma. Para ello, se procesan los resultados de distintos alineadores (HISAT2 y STAR, en ambos tipos de lectura PE y SE) utilizando la herramienta `bamCoverage` de `deepTools`, aplicando normalización por BPM, eliminación de duplicados y omisión de regiones problemáticas mediante una blacklist cuando está disponible. Además, se ajusta el tratamiento de las lecturas según su tipo (PE o SE) y se generan archivos en formato `BigWig`, optimizados para visualización y análisis posteriores.

```{shell Generación de pileups}
#| eval: false
#| echo: true

#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

# Activación del entorno deeptools
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate deeptools

# Directorios y archivos
RESULTS="./results"
BLACKLIST="${RESULTS}/reference/mm38-blacklist.bed"

declare -A rutas
rutas[HISAT2_PE]="${RESULTS}/hisat2_pe"
rutas[HISAT2_SE]="${RESULTS}/hisat2_se"
rutas[STAR_PE]="${RESULTS}/star_pe"
rutas[STAR_SE]="${RESULTS}/star_se"

# Variables útiles
wks=8
BIN_SIZE=20
BAM_FILTERED="BAM_FILTERED_SORTED"

echo "================================================================================================="
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Iniciando la generación de pileups - $current_date_time"

for key in "${!rutas[@]}"; do
    ruta="${rutas[$key]}/$BAM_FILTERED"
    OUT_DIR="${rutas[$key]}/PILEUPS"

    mkdir -p "$OUT_DIR"

    for f in "$ruta"/*.bam; do
        base="$(basename "$f" .bam)"

        echo "-------------------------------------------------------------------------------------------------"

        if [[ "$key" == *_PE ]]; then
            FLAG_INCLUDE=(--samFlagInclude 64)
        else
            FLAG_INCLUDE=()
        fi

        if [[ -f "$BLACKLIST" ]]; then
            echo "Procesando $f con la blacklist $BLACKLIST - [$(date "+%Y-%m-%d %H:%M:%S")]"

            bamCoverage \
                -p "$wks" \
                -b "$f" \
                -o "${OUT_DIR}/${base}.bw" \
                --binSize "$BIN_SIZE" \
                --blackListFileName "$BLACKLIST" \
                --normalizeUsing BPM \
                --skipNAs \
                --ignoreDuplicates \
                "${FLAG_INCLUDE[@]}" \
                --extendReads
        else
            echo "Procesando $f sin blacklist - [$(date "+%Y-%m-%d %H:%M:%S")]"

            bamCoverage \
                -p "$wks" \
                -b "$f" \
                -o "${OUT_DIR}/${base}.bw" \
                --binSize "$BIN_SIZE" \
                --normalizeUsing BPM \
                --skipNAs \
                --ignoreDuplicates \
                "${FLAG_INCLUDE[@]}" \
                --extendReads
        fi

        echo "Procesamiento finalizado - [$(date "+%Y-%m-%d %H:%M:%S")]"
    done
done

echo "-------------------------------------------------------------------------------------------------"
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Script finalizado con éxito - $current_date_time"
echo "================================================================================================="
```

## 3. Feature counts

Se lleva a cabo la primer estrategia de cuantificación de lecturas asignadas a genes mediante `featureCounts`, a partir de los archivos `BAM` previamente filtrados y ordenados. Primero, se descarga y descomprime la anotación genómica de `GENCODE` para ratón en formato `GTF`, necesaria para asociar las lecturas con las características génicas correspondientes. Después, los archivos `BAM` y sus índices se renombran de forma estandarizada incorporando información de la muestra, como el identificador SRR, la edad y el tipo de alineamiento, lo que facilita su organización y trazabilidad. Finalmente, los archivos se ordenan y se procesan con `featureCounts`, ajustando los parámetros según se trate de lecturas PE o SE, para generar tablas de conteo por gen que serán utilizadas en análisis posteriores de expresión.

```{shell Feature counts}
#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

# Descarga de la anotación
URL="https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M38/gencode.vM38.annotation.gtf.gz"
ANNOTATION_DIR="./data/annotation"

mkdir -p "$ANNOTATION_DIR"

# Ejecución de Feature Counts
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate subread

# Variables útiles
wks=8

echo "================================================================================================="
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Iniciando descarga de GTF - $current_date_time"
echo ""

# Descarga de datos
ANNOTATION_GZ="${ANNOTATION_DIR}/gencode.vM38.annotation.gtf.gz"
ANNOTATION="${ANNOTATION_DIR}/gencode.vM38.annotation.gtf"

# Evita volver a descargar si ya estaba
if [[ ! -f "$ANNOTATION" ]]; then
    wget -P "$ANNOTATION_DIR" "$URL" && gunzip -kf "$ANNOTATION_GZ"
fi

echo "-------------------------------------------------------------------------------------------------"
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Descarga exitosa - $current_date_time"
echo "================================================================================================="

# Directorios de trabajo
RESULTS="./results"
BAM_FILTERED="BAM_FILTERED_SORTED"

declare -A rutas
rutas[HISAT2_PE]="${RESULTS}/hisat2_pe"
rutas[HISAT2_SE]="${RESULTS}/hisat2_se"
rutas[STAR_PE]="${RESULTS}/star_pe"
rutas[STAR_SE]="${RESULTS}/star_se"

# Renombrado de archivos
declare -A edades
edades[SRR9126754]="18"
edades[SRR9127244]="3"
edades[SRR9127382]="18"
edades[SRR9127568]="18"
edades[SRR9126950]="3"
edades[SRR9127139]="3"
edades[SRR9126924]="18"

echo "================================================================================================="
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Iniciando renombrado de archivos BAM y BAI - $current_date_time"
echo ""

# Iterando sobre las rutas de cada alineador
for key in "${!rutas[@]}"; do
    dir="${rutas[$key]}/${BAM_FILTERED}"

    # Evalúa si se trata de un directorio o no
    [[ -d "$dir" ]] || continue

    archivos_bam=()
    archivos=("$dir"/*.bam "$dir"/*.bai)

    for file in "${archivos[@]}"; do
        base=$(basename "$file")
        ext="${base##*.}"
        name="${base%.*}"

        # Separa el nombre por "_"
        IFS='_' read -r srr align tipo _ <<< "$name"

        edad="${edades[$srr]:-}"

        if [[ -z "$edad" ]]; then
            echo "No encontré edad para $srr, se omite: $base"
            continue
        fi

        new_name="${srr}_age${edad}_${align}_${tipo}_filtered.${ext}"

        # Desplazando archivos BAI a su respectivo directorio
        if [[ "${ext}" == "bai" ]]; then
            new_dir="${rutas[$key]}/BAI"
            mkdir -p "$new_dir"
            new_path="${new_dir}/${new_name}"
        else
            new_path="${dir}/${new_name}"
        fi

        # Obtención de los nombres de los archivos BAM
        if [[ "${ext}" == "bam" ]]; then
            archivos_bam+=("$new_path")
        fi

        echo "$base -> $new_name"
        echo "Destino: $new_path"
        mv -n -- "$file" "$new_path" # No sobreescribe archivos existentes
        echo "-------------------------------------------------------------------------------------------------"
    done

    # Ordenando los nombres de los archivos para featureCounts dentro de un arreglo
    mapfile -t bams_ordenados < <(printf "%s\n" "${archivos_bam[@]}" | sort)

    # Generación de listas ordenadas
    printf "%s\n" "${bams_ordenados[@]}" > "${rutas[$key]}/bam_${key}_sorted_names.txt"

    echo "================================================================================================="
    current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
    echo "Iniciando FeatureCounts - $current_date_time"
    echo ""

    if [[ ${#bams_ordenados[@]} -eq 0 ]]; then
        echo "No hay BAMs para $key, se omite featureCounts"
        continue
    fi

    # Revisión del tipo de lectura
    if [[ "$key" == *_PE ]]; then
        FEATURECOUNTS_PE=(-p -B)
    else
        FEATURECOUNTS_PE=()
    fi

    # Directorio de salida
    OUT="${rutas[$key]}/FeatureCounts"
    mkdir -p "$OUT"

    featureCounts \
        -T $wks \
        -a "$ANNOTATION" \
        -o "$OUT/counts_${key}_table.txt" \
        --largestOverlap \
        -s 0 \
        "${FEATURECOUNTS_PE[@]}" \
        "${bams_ordenados[@]}"

    current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
    echo "FeatureCounts finalizado, tabla guardada en "$OUT" - $current_date_time"
    echo "================================================================================================="
done

current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Script finalizado - $current_date_time"
echo "================================================================================================="
```

## 4. Pseudoalineamientos

En contraste con la sección previa, donde la cuantificación se realiza a partir de alineamientos completos mediante `featureCounts`, en esta sección se implementa un enfoque alternativo basado en pseudoalineamientos utilizando `Salmon`. Aquí, las lecturas previamente procesadas (tras control de calidad) se asignan directamente a transcritos de referencia sin necesidad de generar archivos `BAM`, lo que permite una estimación más eficiente de la abundancia transcriptómica. Para ello, se identifican las muestras a partir de los archivos `FASTQ`, se manejan de acuerdo con su tipo de lectura y se cuantifican contra un índice transcriptómico preconstruido. El resultado consiste en estimaciones de abundancia a nivel de transcrito por muestra, que pueden compararse posteriormente con los obtenidos mediante métodos basados en alineamiento.

```{shell Pseudoalineamientos con Salmon}
#| eval: false
#| echo: true

#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

# Directorios de trabajo
DATA="./data"
RESULTS="./results"
FASTQ_CLEANED="${DATA}/fastp"
SALMON_DIR="${RESULTS}/SALMON"

mkdir -p "$SALMON_DIR"

# Variables útiles
wks=8
READ_TYPE="paired"
SALMON_IDX="${DATA}/indexes/mm39.gencode.M36.salmon"

# Entorno de salmon
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate salmon

echo "================================================================================================="
current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Iniciando pseudoalineamientos con SALMON - $current_date_time"
echo ""
echo "-------------------------------------------------------------------------------------------------"

# Obtención de nombres de muestra
fastq_array=("${FASTQ_CLEANED}"/*.fastq)
mapfile -t nombres < <(
    for f in "${fastq_array[@]}"; do
        base=$(basename "$f")
        echo "${base%%_clean*}"
    done | sort -u
)

for sample in "${nombres[@]}"; do
    echo "-------------------------------------------------------------------------------------------------"
    echo "Procesando muestra ${sample}... - [$(date "+%Y-%m-%d %H:%M:%S")]"
    echo "Tipo de lectura: $READ_TYPE"
    echo ""

    OUT="${SALMON_DIR}/$sample"

    if [[ "$READ_TYPE" == "paired" ]]; then

        R1="${FASTQ_CLEANED}/${sample}_clean_1.fastq"
        R2="${FASTQ_CLEANED}/${sample}_clean_2.fastq"

        if [[ ! -f "$R1" || ! -f "$R2" ]]; then
            echo "No está uno de los pares de la muestra $sample"
            continue
        fi

        salmon quant \
            -i "$SALMON_IDX" \
            -l A \
            -1 "$R1" \
            -2 "$R2" \
            -p "$wks" \
            --validateMappings \
            -o "$OUT"

    else

        R="${FASTQ_CLEANED}/${sample}_clean.fastq"

        if [[ ! -f "$R" ]]; then
            echo "Sin archivo para la muestra $sample"
            continue
        fi

        salmon quant \
            -i "$SALMON_IDX" \
            -l A \
            -r "$R" \
            -p "$wks" \
            --validateMappings \
            -o "$OUT"
    fi

    echo "Fin del procesamiento - [$(date "+%Y-%m-%d %H:%M:%S")]"
    echo "-------------------------------------------------------------------------------------------------"
done

current_date_time="$(date "+%Y-%m-%d %H:%M:%S")"
echo "Script finalizado con éxito - $current_date_time"
echo "================================================================================================="
```

## 3. `tximport`

Dando continuidad a la cuantificación obtenida mediante pseudoalineamientos con `Salmon`, en esta sección se integran y transforman dichas estimaciones a nivel génico utilizando el puerto en Python de `tximport`. Para ello, primero se construye un mapa de correspondencia entre transcritos y genes a partir de la anotación `GTF` (`tx2gene`), eliminando las versiones de los identificadores para asegurar consistencia. Posteriormente, se filtran y organizan las muestras de interés con base en su `SRR[0-9]+` y edad, generando nombres estandarizados que facilitan su trazabilidad. Finalmente, se importan los archivos `quant.sf` generados por `Salmon` y se agregan a nivel de gen mediante `tximport`, aplicando una corrección basada en la longitud y TPM, lo que produce matrices de conteo listas para análisis downstream de expresión diferencial.

```{python tximport}
#| eval: false
#| echo: true
#| message: false

from pytximport.utils import create_transcript_gene_map_from_annotation
from pytximport import tximport
import pandas as pd
import os
import re

def get_files_list(dir: str = "results") -> list[str]:
    if not os.path.isdir(dir):
        msg = f"[FILES] The given path don't correspond to a directory: {dir}"
        raise ValueError(msg)
    files = [file for f in sorted(os.listdir(dir)) if os.path.isfile(file := (os.path.join(dir, f)))]
    return files

def get_dirs_list(dir: str = "results") -> list[str]:
    if not os.path.isdir(dir):
        msg = f"[FILES] The given path don't correspond to a directory: {dir}"
        raise ValueError(msg)
    dirs = [path_dir for f in sorted(os.listdir(dir)) if os.path.isdir(path_dir := os.path.join(dir, f))]
    return dirs

# Mapa transcrito a gen
tx2gene = create_transcript_gene_map_from_annotation("./data/annotation/gencode.vM38.annotation.gtf")
tx2gene.to_csv("./results/tx2gene.csv", sep=",", index=False)

# Eliminando la versión en los gene y transcript ID
tx2gene["transcript_id"] = tx2gene["transcript_id"].str.replace(r"\.[0-9]$", "", regex=True)
tx2gene["gene_id"] = tx2gene["gene_id"].str.replace(r"\.[0-9]$", "", regex=True)

# Metadata
metadata = pd.read_csv("data/GSE132040_MACA_Bulk_metadata.csv")
patt_tissue = re.compile(r"^kidney(.?)+", re.IGNORECASE)
metadata = metadata[
    ((metadata["characteristics: age"] == "3") | (metadata["characteristics: age"] == "18")) &
    ((metadata["characteristics: sex"] == "m") & (metadata["source name"].astype(str).str.match(patt_tissue)))
]
SRR_files = list(metadata["raw file"])
SRR_age = list((metadata["characteristics: age"]))

files_age = {
    srr : SRR_age[idx]
    for idx, srr in enumerate(SRR_files)
}

# Obtención de las asignaciones de pseudo-conteos
salmon_se, salmon_pe = get_dirs_list("results/SALMON/SE"), get_dirs_list("results/SALMON/PE")
read_dir_type = "results/SALMON/SE", "results/SALMON/PE"
read_type = "pe", "se"
i = 0

for salmon_type in (salmon_pe, salmon_pe):

    files = []
    new_names = []

    for dir in salmon_type:

        file = f"{dir}/quant.sf"
        assert os.path.isfile(file), f"No existe el archivo {file}"

        sample = os.path.basename(dir)
        new_name = f"{sample}_{files_age[sample]}_{read_type[i]}"

        files.append(file)
        new_names.append(new_name)
    
    # Metadata
    pd.DataFrame({
        "File" : files,
        "Sample" : new_names
    }).to_csv(os.path.join(read_dir_type[i], f"metadata_{read_type[i]}.csv"), index=False, sep=",")

    # pytximport
    results = tximport(
        files,
        data_type="salmon",
        transcript_gene_map=tx2gene,
        counts_from_abundance="length_scaled_tpm",
        output_format="csv",
        output_path=f"{read_dir_type[i]}/salmon_counts_{read_type[i]}.csv",
        output_path_overwrite=True
    )

    i += 1
```

# Discusión

[...]

```{python Figura 1. Relación de retención entre la retención de lecturas y los alineadores}
#| echo: false
#| eval: true
#| message: true
#| warning: false
#| fig-cap: Relación de retención entre la retención de lecturas y los alineadores.

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Cargando datos
bam_reads = pd.read_csv("results/bam_reads.csv", sep=",")

# Descomposición de labels
bam_reads[
    ["Muestra", "Alineador", "Tipo de lectura"]
] = bam_reads["aligner"].str.upper().str.split("_", expand=True)

bam_reads["Retención (%)"] = bam_reads["processed"] / bam_reads["raw"]

bam_reads.columns = ['aligner', 'Crudas', 'Procesadas', 'Muestra', 'Alineador', 'Tipo de lectura', 'Retención (%)']

df_long = bam_reads.melt(
    id_vars=["Muestra", "Alineador", "Tipo de lectura"],
    value_vars=["Crudas", "Procesadas"],
    var_name="Estado",
    value_name="Lecturas"
)

plt.close("all")

sns.lmplot(
    data=bam_reads,
    x="Crudas",
    y="Procesadas",
    hue="Tipo de lectura",
    col="Alineador",
    palette=sns.color_palette("viridis", 2)
)

plt.show()
```



# Conclusiones

[...]

# Referencias